import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster, toast } from "sonner";

import "./globals.css";
import '../styles/index.scss'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ship·Fast",
  description: "Generated by create Ship·Fast",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster position="top-center" richColors />
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
